from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
QUESTIONS_PATH = ROOT / "data" / "questions.json"

BANK_ID = "web-curated-pmbok7-200"
BANK_TITLE = "PMBOK 7 Web Curated 200"
BANK_SOURCE = "Original web-researched PMBOK 7 question bank (compiled May 17, 2026)"

OPTION_KEYS = ["A", "B", "C", "D"]
QUESTION_BLUEPRINTS: list[tuple[str, str, str, list[str]]] = []


def build_question(prompt_number: int, topic: str, stem: str, correct: str, distractors: list[str]) -> dict:
    correct_slot = (prompt_number - 1) % 4
    correct_option = OPTION_KEYS[correct_slot]
    distractor_iter = iter(distractors)
    options = []

    for index, key in enumerate(OPTION_KEYS):
        if index == correct_slot:
            text = correct
        else:
            text = next(distractor_iter)
        options.append({"key": key, "text": text})

    return {
        "id": prompt_number,
        "promptNumber": prompt_number,
        "topic": topic,
        "source": BANK_SOURCE,
        "stem": stem,
        "options": options,
        "correctOption": correct_option,
    }


def q(topic: str, stem: str, correct: str, d1: str, d2: str, d3: str) -> tuple[str, str, str, list[str]]:
    return topic, stem, correct, [d1, d2, d3]


QUESTION_BLUEPRINTS.extend(
    [
        q(
            "Stakeholders",
            "A sponsor asks to reduce features late in a project because market conditions changed. The product owner believes the original scope should remain unchanged. What should the project manager do first?",
            "Facilitate a discussion to review the changed business need and evaluate the impact on value delivery.",
            "Reject the request because the baseline has already been approved.",
            "Ask the development team to remove the least expensive features immediately.",
            "Escalate the disagreement to procurement because the product owner is blocking progress.",
        ),
        q(
            "Stakeholders",
            "A stakeholder who was previously neutral has started influencing team members against a process change. What is the best next action?",
            "Meet with the stakeholder to understand the concern and update the engagement approach if needed.",
            "Remove the stakeholder from project communications until the resistance stops.",
            "Ask the sponsor to publicly overrule the stakeholder.",
            "Delay the change until the next phase so conflict can be avoided.",
        ),
        q(
            "Stakeholders",
            "In a hybrid project, business users say they feel surprised by each release even though demos are occurring every two weeks. What should the project manager improve first?",
            "The feedback and engagement mechanism so users influence priorities before each release.",
            "The defect log so surprises are categorized more carefully.",
            "The cost baseline so each release is funded separately.",
            "The procurement strategy so vendors can attend the demos.",
        ),
        q(
            "Stakeholders",
            "A key external customer misses several review meetings and later objects to a delivered feature. Which action best aligns with PMBOK 7 stakeholder thinking?",
            "Reassess stakeholder needs and tailor the review approach to secure timely involvement.",
            "Freeze all requirements until the customer confirms future attendance.",
            "Issue a formal warning that acceptance is implied when meetings are missed.",
            "Have the team continue without customer input to preserve schedule stability.",
        ),
        q(
            "Stakeholders",
            "A project team has excellent technical output, but adoption remains low because operations staff were not consulted. What should have been emphasized more strongly?",
            "Proactive stakeholder engagement throughout delivery.",
            "Tighter control of variance thresholds.",
            "A larger contingency reserve.",
            "A stricter change freeze window.",
        ),
        q(
            "Stakeholders",
            "During backlog refinement, two powerful stakeholders request conflicting priorities. What should the project manager do first?",
            "Use agreed prioritization criteria tied to benefits and facilitate a decision.",
            "Split the backlog equally between both stakeholders to preserve fairness.",
            "Ask the team to choose whichever work is easier to estimate.",
            "Escalate immediately because conflicting priorities always require governance action.",
        ),
        q(
            "Stakeholders",
            "A business unit wants status in a dashboard, while regulators require signed monthly reports. What is the best PMBOK 7 response?",
            "Tailor communications so each stakeholder receives the format needed for sound decisions and compliance.",
            "Use only one reporting format so the team is not distracted by stakeholder preferences.",
            "Provide the signed monthly report to everyone because formal reporting is safer.",
            "Provide the dashboard only because current data is more valuable than formal records.",
        ),
        q(
            "Stakeholders",
            "A project manager learns that an influential stakeholder is using outdated assumptions from an early workshop. What should the project manager do next?",
            "Correct the misunderstanding quickly and verify that future communications reflect current decisions.",
            "Wait until the next steering committee so the entire group hears the correction at once.",
            "Avoid engaging the stakeholder directly because the issue may resolve itself.",
            "Ask the team lead to ignore any requests from that stakeholder.",
        ),
        q(
            "Stakeholders",
            "A customer representative keeps adding requests in side conversations with engineers. What should the project manager do first?",
            "Reinforce the agreed engagement and change path while preserving the relationship with the customer.",
            "Tell the engineers to reject all customer requests until project closeout.",
            "Move the representative off the project to eliminate disruption.",
            "Accept the requests because satisfying the customer is the top priority.",
        ),
        q(
            "Stakeholders",
            "A project will affect warehouse staff on every shift, but only day-shift users attend workshops. Which action is best?",
            "Broaden stakeholder participation so decisions reflect all affected groups.",
            "Proceed with the available input to avoid analysis paralysis.",
            "Assume day-shift staff can speak for the entire workforce.",
            "Ask the sponsor to choose requirements on behalf of operations.",
        ),
        q(
            "Stakeholders",
            "Mid-project, a merger introduces a new executive who questions the initiative's purpose. What should the project manager do first?",
            "Reconfirm strategic alignment and expected benefits with the new decision makers.",
            "Pause the project until the merger is complete.",
            "Defend the original charter without revisiting assumptions.",
            "Ask the team to accelerate delivery so the executive cannot change direction.",
        ),
        q(
            "Stakeholders",
            "Community members support a construction project overall but oppose weekend work. Which action best reflects effective stakeholder engagement?",
            "Assess the concern, evaluate alternatives, and adjust the execution approach where feasible.",
            "Continue weekend work because the broader project still has support.",
            "Transfer ownership of community communications to the contractor.",
            "Treat the concern as a team issue instead of a stakeholder issue.",
        ),
        q(
            "Stakeholders",
            "A stakeholder requests more detailed status than the team can provide without excessive overhead. What should the project manager do?",
            "Discuss the decision need behind the request and tailor reporting to provide useful information efficiently.",
            "Produce every detail requested because stakeholder satisfaction outweighs team efficiency.",
            "Deny the request because the communications plan cannot be changed.",
            "Replace the stakeholder contact with someone less demanding.",
        ),
        q(
            "Stakeholders",
            "A vendor says a requirement was ambiguous, while the customer insists it was obvious. What should the project manager do first?",
            "Review the requirement and acceptance understanding with both parties before assigning blame.",
            "Approve a change request because ambiguity automatically changes scope.",
            "Side with the customer because the customer funds the project.",
            "Apply a contract penalty because misunderstanding indicates poor vendor performance.",
        ),
        q(
            "Stakeholders",
            "Which action best demonstrates the PMBOK 7 principle related to stakeholders?",
            "Engaging stakeholders proactively and to the degree needed to support success.",
            "Restricting stakeholder access to protect the team from change.",
            "Deferring communication until deliverables are complete.",
            "Treating all stakeholders identically regardless of influence or impact.",
        ),
        q(
            "Stakeholders",
            "A product launch requires coordination across legal, sales, support, and engineering. Which artifact is most likely to help the project manager plan targeted engagement?",
            "A stakeholder engagement plan.",
            "A procurement statement of work.",
            "A cost baseline.",
            "A burnup chart.",
        ),
        q(
            "Stakeholders",
            "Team morale is dropping because stakeholders keep changing their minds after demos. What should the project manager do first?",
            "Clarify decision rights, acceptance expectations, and feedback timing with stakeholders.",
            "Reduce the number of demos so fewer changes are requested.",
            "Tell the team to stop accepting stakeholder feedback once work begins.",
            "Move to a purely predictive approach regardless of context.",
        ),
        q(
            "Stakeholders",
            "An executive wants every low-level task escalated, causing delays and undermining the team. What should the project manager do?",
            "Set appropriate governance boundaries and keep the executive focused on decisions at the right level.",
            "Escalate even more frequently so the executive feels fully informed.",
            "Remove the executive from all communications.",
            "Allow engineers to bypass the project manager and reply directly.",
        ),
        q(
            "Stakeholders",
            "A project manager inherits a project with a complete stakeholder register but no sign of meaningful engagement. What is the main problem?",
            "Identifying stakeholders is not enough without active strategies and actions to involve them productively.",
            "A stakeholder register should never be created until the end of planning.",
            "Engagement is optional once stakeholders are documented.",
            "Only sponsors need engagement strategies.",
        ),
        q(
            "Stakeholders",
            "What is the best indicator that stakeholder engagement is working?",
            "Stakeholders receive and use the right information to make timely decisions and support outcomes.",
            "The project manager sends the same report to everyone every week.",
            "No stakeholder ever raises an issue.",
            "The number of emails sent increases each month.",
        ),
        q(
            "Team",
            "A capable team keeps waiting for the project manager to assign every task. What leadership response is best in an adaptive environment?",
            "Coach the team toward greater self-management and shared ownership.",
            "Increase task-level direction so nothing is missed.",
            "Have the sponsor assign work directly to remove delay.",
            "Delay decision making until all assignments can be documented in detail.",
        ),
        q(
            "Team",
            "A new specialist joins a high-performing team and tension rises because work habits differ. What should the project manager do first?",
            "Support team integration by clarifying norms, roles, and collaboration expectations.",
            "Reassign the specialist before team performance declines.",
            "Ignore the tension because high-performing teams should solve it alone.",
            "Freeze all process changes until the specialist adjusts personally.",
        ),
        q(
            "Team",
            "Which action best aligns with the PMBOK 7 team principle?",
            "Creating an environment where the team can evolve into a high-performing group.",
            "Separating technical experts so they work independently and faster.",
            "Preventing leadership behavior from emerging outside the project manager.",
            "Using competition between team members as the main motivational tool.",
        ),
        q(
            "Team",
            "A conflict between two team members is slowing delivery. What should the project manager do first?",
            "Address the conflict directly and facilitate a constructive resolution.",
            "Document the conflict in lessons learned and revisit it after release.",
            "Move both team members to different workstreams without discussion.",
            "Ask the sponsor to select which team member is correct.",
        ),
        q(
            "Team",
            "A remote team works across three time zones and participation in retrospectives is low. What is the best next action?",
            "Adapt the retrospective format and timing so the team can contribute meaningfully.",
            "Cancel retrospectives because remote teams cannot use them effectively.",
            "Make attendance optional and stop collecting improvement ideas.",
            "Replace asynchronous input with one fixed meeting time for everyone permanently.",
        ),
        q(
            "Team",
            "A project manager notices one senior engineer dominates sprint planning while others stay silent. What should the project manager do?",
            "Facilitate balanced participation so planning reflects the whole team's knowledge.",
            "Let the senior engineer continue because expertise should override collaboration.",
            "Escalate the issue to human resources before speaking to the team.",
            "Assign all planning decisions to the product owner.",
        ),
        q(
            "Team",
            "A team is meeting delivery dates but accumulating avoidable rework. Which response best supports long-term performance?",
            "Build quality into the way the team works and learn from recurring defects.",
            "Accept the rework as the normal cost of staying on schedule.",
            "Delay all testing until the end of the phase to reduce interruptions.",
            "Reduce collaboration time so more hours go to development.",
        ),
        q(
            "Team",
            "A highly experienced team asks for fewer approval gates so it can deliver faster. What should the project manager do first?",
            "Evaluate whether governance can be tailored without undermining risk, quality, or compliance.",
            "Approve the request immediately because experienced teams need no oversight.",
            "Reject the request because governance can never be tailored.",
            "Escalate to procurement because gates affect vendor performance.",
        ),
        q(
            "Team",
            "A manager outside the project assigns urgent work directly to team members, disrupting commitments. What should the project manager do first?",
            "Clarify priorities and governance with the manager while protecting team focus.",
            "Tell the team to ignore all outside requests regardless of business need.",
            "Allow the interruptions because managers outrank project priorities.",
            "Reduce team visibility so outside managers cannot contact members.",
        ),
        q(
            "Team",
            "Which leadership behavior best fits PMBOK 7 guidance in a project environment?",
            "Adapting leadership style to the situation while modeling ethical conduct.",
            "Applying one fixed management style to preserve consistency.",
            "Avoiding difficult conversations to maintain harmony.",
            "Using authority first and collaboration only as a last resort.",
        ),
        q(
            "Team",
            "A project manager wants immediate trust from a newly formed team. Which action is most effective first?",
            "Create clarity on goals, roles, and working agreements while listening actively to concerns.",
            "Increase reporting requirements so everyone proves accountability quickly.",
            "Avoid discussing roles until the team naturally settles in.",
            "Focus only on schedule compression to demonstrate urgency.",
        ),
        q(
            "Team",
            "A team member raises a risk but says no one listens to concerns. What should the project manager do?",
            "Encourage psychological safety and reinforce that surfacing risks is valuable behavior.",
            "Ask the team member to bring up risks only after they become issues.",
            "Tell the team member to stop raising risks unless mitigation is already funded.",
            "Move risk discussions to executive meetings only.",
        ),
        q(
            "Team",
            "A team consistently misses commitments because members overcommit to impress leadership. What should the project manager do first?",
            "Use transparent planning and data to create realistic commitments.",
            "Increase the commitments further so performance pressure rises.",
            "Remove estimation and let tasks continue without targets.",
            "Penalize the team publicly for missed commitments before planning again.",
        ),
        q(
            "Team",
            "A project manager wants the team to learn from each release rather than repeat the same mistakes. Which practice best supports this?",
            "Regular retrospectives and follow-through on agreed improvements.",
            "Deferring all lessons learned until project closeout.",
            "Tracking only budget variance because delivery metrics are enough.",
            "Changing team membership after every release.",
        ),
        q(
            "Team",
            "Which action best reflects servant leadership in a project setting?",
            "Removing obstacles so the team can deliver value effectively.",
            "Controlling every task assignment personally.",
            "Shielding the team from all stakeholder feedback.",
            "Limiting the team to only sponsor-approved ideas.",
        ),
        q(
            "Team",
            "A project involves specialists from several departments who prioritize functional goals over project goals. What should the project manager do first?",
            "Create shared project objectives and clarify accountability across the team structure.",
            "Ask each department to optimize its own work independently.",
            "Avoid discussing tradeoffs until the first escalation occurs.",
            "Move all decisions to the steering committee immediately.",
        ),
        q(
            "Team",
            "A team produces strong results but burns out because urgent work never slows. Which response is best?",
            "Adjust the operating approach to sustain performance and resiliency over time.",
            "Push harder until the current release is complete, then revisit well-being later.",
            "Add more work so the team can clear the backlog faster.",
            "Eliminate reflection sessions because they take time away from delivery.",
        ),
        q(
            "Team",
            "A project manager wants more innovation from the team. What should the project manager do first?",
            "Create a safe environment for experimentation and constructive learning.",
            "Require all ideas to be sponsor-approved before discussion.",
            "Reduce cross-functional input so decisions are faster.",
            "Use only proven practices and avoid trying anything new.",
        ),
        q(
            "Team",
            "Which outcome best shows a team has matured into high performance?",
            "The team collaborates, adapts, and shares ownership for outcomes.",
            "Every decision is routed through the project manager.",
            "Team members work alone to maximize specialization.",
            "Conflict is hidden rather than addressed.",
        ),
        q(
            "Approach & Life Cycle",
            "A project has stable requirements, high regulatory documentation needs, and very costly late changes. Which development approach is most appropriate initially?",
            "Predictive.",
            "Adaptive.",
            "Hybrid with no upfront planning.",
            "Continuous flow with no baseline controls.",
        ),
        q(
            "Approach & Life Cycle",
            "A product discovery effort has rapidly changing requirements and benefits from frequent feedback. Which approach best fits?",
            "Adaptive.",
            "Purely predictive.",
            "A fixed phase-gate approach with one final release.",
            "A procurement-led approach regardless of uncertainty.",
        ),
        q(
            "Approach & Life Cycle",
            "Hardware components are fixed early, but the software interface will evolve through user feedback. What approach is most suitable?",
            "Hybrid.",
            "Predictive for everything.",
            "Adaptive for everything.",
            "No defined approach until execution starts.",
        ),
        q(
            "Approach & Life Cycle",
            "Which factor should most strongly influence the initial choice of development approach?",
            "The nature of the deliverables and the level of uncertainty around them.",
            "The personal preference of the loudest stakeholder.",
            "Whether the team used Scrum on the last project.",
            "The number of people on the steering committee.",
        ),
        q(
            "Approach & Life Cycle",
            "A team selected a predictive approach during initiation. Midway through the project, customer needs begin changing monthly. What should the project manager do first?",
            "Reassess whether the current approach remains appropriate and tailor if needed.",
            "Keep the original approach unchanged because tailoring after initiation is poor practice.",
            "Cancel the project and restart under agile governance.",
            "Ignore the change pattern until the baseline is missed.",
        ),
        q(
            "Approach & Life Cycle",
            "A project manager is tailoring a hybrid approach. Which decision belongs in that tailoring effort?",
            "How iterative delivery will coexist with required governance reviews.",
            "Whether project ethics still apply in the selected approach.",
            "Whether stakeholders should be identified at all.",
            "Whether risk should be considered only after execution starts.",
        ),
        q(
            "Approach & Life Cycle",
            "A sponsor asks why a hybrid approach was chosen. What is the best explanation?",
            "Different parts of the work benefit from different delivery cadences and controls.",
            "Hybrid is always better than predictive or adaptive approaches.",
            "Hybrid eliminates the need for planning and governance.",
            "Hybrid should be used whenever the team wants more autonomy.",
        ),
        q(
            "Approach & Life Cycle",
            "Which statement best reflects PMBOK 7 tailoring guidance?",
            "Tailoring is iterative and continues throughout the project.",
            "Tailoring happens once during planning and should not change later.",
            "Tailoring applies only to agile projects.",
            "Tailoring means removing as many controls as possible.",
        ),
        q(
            "Approach & Life Cycle",
            "A release cadence is causing stakeholder fatigue because demos happen too frequently for the business. What should the project manager do?",
            "Adjust the cadence to balance feedback value with stakeholder capacity.",
            "Continue the cadence because all short cycles are inherently better.",
            "Switch to yearly releases immediately.",
            "Stop collecting stakeholder feedback until deployment.",
        ),
        q(
            "Approach & Life Cycle",
            "Which PMBOK 7 principle most directly supports selecting predictive, adaptive, or hybrid based on context?",
            "Tailoring.",
            "Stewardship.",
            "Quality.",
            "Change.",
        ),
    ]
)

QUESTION_BLUEPRINTS.extend(
    [
        q(
            "Measurement",
            "A project manager tracks sprint velocity carefully, but dependency delays from another team still derail releases. What should improve?",
            "Measurement should include system-level constraints, not just local team output.",
            "Velocity should be doubled to compensate.",
            "All dependency tracking should be removed.",
            "The project should stop using iterative delivery.",
        ),
        q(
            "Measurement",
            "A sponsor asks for a single metric to prove success. What is the best answer?",
            "No single metric is enough; success should be assessed through a balanced view tied to intended outcomes.",
            "Schedule performance alone proves success.",
            "Cost variance alone proves success.",
            "Feature count alone proves success.",
        ),
        q(
            "Measurement",
            "A team meets all internal targets, but the market window is closing fast. Which measurement gap is most likely?",
            "The team is not measuring performance against external business timing and value realities.",
            "The team is using too many customer-focused indicators.",
            "The team has too many retrospectives.",
            "The team is overusing quality checks.",
        ),
        q(
            "Measurement",
            "Which outcome best shows healthy project measurement?",
            "Timely, accurate information leads to effective action and learning.",
            "Metrics are collected but never discussed.",
            "Reports are longer every month.",
            "Only positive trends are shared upward.",
        ),
        q(
            "Measurement",
            "A project manager is comparing planned and actual delivery, but the scope itself changed significantly. What should happen?",
            "Interpret measurement in context and update the planning basis as appropriate.",
            "Ignore the scope change when assessing performance.",
            "Measure only cost because scope changed.",
            "Stop all reporting until the project closes.",
        ),
        q(
            "Uncertainty",
            "A project faces uncertain regulations in a new market. Which action is best first?",
            "Assess the uncertainty early and define responses that are realistic in the project context.",
            "Assume the regulations will remain stable because research is incomplete.",
            "Ignore the market until product launch.",
            "Treat the uncertainty as a team morale issue only.",
        ),
        q(
            "Uncertainty",
            "Which statement best reflects the Uncertainty Performance Domain?",
            "Projects face both threats and opportunities that should be explored, assessed, and handled deliberately.",
            "Uncertainty management applies only after a risk becomes an issue.",
            "Uncertainty is the same thing as scope creep.",
            "Only financial risks matter for project outcomes.",
        ),
        q(
            "Uncertainty",
            "A team identifies a possible vendor failure but no response owner. Why is this weak?",
            "Responses should be owned by a responsible person to be actionable.",
            "Ownership is needed only for positive risks.",
            "The risk is invalid unless it already happened.",
            "Risk ownership belongs exclusively to the sponsor.",
        ),
        q(
            "Uncertainty",
            "A project manager is deciding whether to mitigate, accept, or escalate a threat. Which factor matters most?",
            "The significance of the risk and the practicality of the response in context.",
            "Whether the response sounds decisive in status meetings.",
            "Whether the response creates more documentation.",
            "Whether the team dislikes discussing the risk.",
        ),
        q(
            "Uncertainty",
            "An emerging opportunity could create major benefit, but the team is too focused on threats to notice it. What should the project manager do?",
            "Broaden uncertainty discussions to include opportunities as well as threats.",
            "Ignore the opportunity because PMP risk work is only about negative events.",
            "Record the opportunity as a defect instead.",
            "Wait until the opportunity becomes certain before mentioning it.",
        ),
        q(
            "Uncertainty",
            "A risk workshop produces a long list of vague statements like 'things may go wrong.' What should the project manager improve?",
            "The clarity and usefulness of risk identification so responses can be practical.",
            "The number of stakeholders attending lunch sessions.",
            "The team's access to retrospective notes only.",
            "The frequency of cost reporting.",
        ),
        q(
            "Uncertainty",
            "A complex initiative has ambiguous responsibilities and interdependent systems. Which form of uncertainty is especially relevant?",
            "Complexity-related uncertainty.",
            "Only schedule variance.",
            "Only procurement pricing uncertainty.",
            "No meaningful uncertainty because the charter was approved.",
        ),
        q(
            "Uncertainty",
            "A project manager wants to spend contingency on every possible risk response. What should happen first?",
            "Prioritize responses that are cost-effective and proportionate to significance.",
            "Use all reserves early so no funds remain idle.",
            "Spend the contingency equally across all listed risks.",
            "Move all risk funds into team rewards.",
        ),
        q(
            "Uncertainty",
            "A new technology may accelerate delivery, but its behavior under load is not proven. What is the best next step?",
            "Run a controlled assessment or experiment to reduce uncertainty before broad commitment.",
            "Adopt it everywhere immediately because innovation should not be slowed.",
            "Reject it permanently because any uncertainty is unacceptable.",
            "Ignore the technology until final testing.",
        ),
        q(
            "Uncertainty",
            "A project manager says, 'We already have a risk register, so uncertainty is handled.' What is the main flaw?",
            "A register alone is not enough without ongoing assessment, ownership, and response action.",
            "A risk register should be created only at closing.",
            "Registers are unnecessary in adaptive work.",
            "Uncertainty can be managed only with simulation.",
        ),
        q(
            "Uncertainty",
            "An issue occurs that was not previously identified. What should the project manager do after stabilizing the situation?",
            "Capture learning and consider what should change in future uncertainty management.",
            "Delete the issue because it was not forecast.",
            "Avoid discussing it so stakeholder confidence stays high.",
            "Convert the issue into a closed risk immediately.",
        ),
        q(
            "Uncertainty",
            "A project involves unknown legal interpretations, evolving customer behavior, and a novel technology stack. What should the project manager recognize?",
            "Uncertainty has multiple forms beyond simple probability-based risks.",
            "All uncertainty can be expressed fully with one probability number.",
            "Only technology uncertainty matters because the stack is new.",
            "Customer behavior uncertainty is outside project scope.",
        ),
        q(
            "Uncertainty",
            "Which response best matches PMBOK 7 risk guidance?",
            "Choose a response that is realistic, appropriate to significance, and agreed by relevant stakeholders.",
            "Choose the most expensive response because strong action is persuasive.",
            "Choose whichever response creates the most documentation.",
            "Choose no response until the risk definitely occurs.",
        ),
        q(
            "Uncertainty",
            "A team member says uncertainty makes planning useless. What should the project manager say?",
            "Uncertainty increases the need for thoughtful planning and adaptation, not the opposite.",
            "Uncertainty means all schedules should be removed permanently.",
            "Uncertainty affects only finance, not delivery.",
            "Uncertainty is resolved by motivation alone.",
        ),
        q(
            "Uncertainty",
            "A project manager sees that multiple small risks point to the same root cause. What is the best next step?",
            "Address the shared cause where practical rather than treating each symptom separately.",
            "Log each risk separately and avoid looking for patterns.",
            "Close the smaller risks because they are individually minor.",
            "Transfer all risks to the vendor regardless of contracts.",
        ),
        q(
            "Value & Business",
            "Which statement best reflects the PMBOK 7 value principle?",
            "Project teams should continually evaluate and adjust alignment to intended benefits and business objectives.",
            "Once scope is approved, value no longer needs to be reconsidered.",
            "Value is measured only by keeping cost below baseline.",
            "Only the sponsor is responsible for value delivery thinking.",
        ),
        q(
            "Value & Business",
            "A project is on time and on budget, but expected benefits no longer justify the remaining spend. What should the project manager do first?",
            "Raise the issue and reassess continued alignment to business value.",
            "Continue unchanged because schedule and budget define success.",
            "Hide the concern until the next fiscal year.",
            "Ask the team to add features so the project appears more useful.",
        ),
        q(
            "Value & Business",
            "A sponsor asks for a recommendation on whether to continue a troubled initiative. What should the project manager emphasize?",
            "Current progress, remaining cost, and whether the intended value still warrants continuation.",
            "Only the amount already spent because sunk cost should drive the decision.",
            "Only team morale because business value can be reviewed later.",
            "Only the original schedule promise.",
        ),
        q(
            "Value & Business",
            "A project manager is choosing between two features. One has high visibility but little business impact; the other has moderate visibility but directly supports the primary benefit. Which should come first?",
            "The feature that more directly supports the primary intended benefit.",
            "The feature with higher executive visibility regardless of impact.",
            "The feature with the longest implementation time.",
            "Whichever feature was proposed first in planning.",
        ),
        q(
            "Value & Business",
            "What is the best reason to connect project work to organizational strategy?",
            "It helps ensure effort and spending advance meaningful outcomes rather than activity alone.",
            "Strategy matters only to portfolio managers, not projects.",
            "Strategic alignment reduces the need for stakeholder engagement.",
            "Projects should remain operationally isolated from business goals.",
        ),
        q(
            "Value & Business",
            "A project produces a compliant solution, but users adopt a competitor's tool instead. What should the project manager examine?",
            "Whether the project's delivered outcome is still aligned to stakeholder value and market reality.",
            "Only the technical architecture.",
            "Only the daily standup agenda.",
            "Only the project naming convention.",
        ),
        q(
            "Value & Business",
            "Which action best supports value delivery in a changing environment?",
            "Reprioritizing work when new information changes the expected benefit profile.",
            "Protecting the original plan even when value assumptions change.",
            "Deferring all benefit discussions until project closeout.",
            "Avoiding stakeholder feedback once execution starts.",
        ),
        q(
            "Value & Business",
            "A company launched a project to reduce compliance penalties. Six months later, penalties are already down because of a policy change outside the project. What should the project manager do?",
            "Reassess the business case and remaining project value before continuing unchanged.",
            "Continue unchanged because stopping would look inconsistent.",
            "Increase scope to use the remaining budget.",
            "Ignore the policy change because it is external.",
        ),
        q(
            "Value & Business",
            "A PMO asks teams to report outputs completed. An executive asks instead whether outcomes are improving. What is the difference?",
            "Outputs are what the project produces; outcomes are the effects those outputs create.",
            "Outputs and outcomes are interchangeable terms.",
            "Outcomes are always internal while outputs are external.",
            "Only procurement projects distinguish outputs from outcomes.",
        ),
        q(
            "Value & Business",
            "A project is delivering a customer portal. Which measure best reflects business value more directly than feature count?",
            "Reduction in support calls or improved customer completion rates.",
            "The number of files in the repository.",
            "The number of internal status meetings held.",
            "The count of project assumptions documented.",
        ),
        q(
            "Value & Business",
            "A sponsor wants to add low-value work simply because funding is available. What should the project manager do?",
            "Challenge the addition using value-based reasoning and organizational objectives.",
            "Add the work because unused funding should always be consumed.",
            "Let the team pick arbitrary features to fill the budget.",
            "Hide the remaining funds to avoid stakeholder interest.",
        ),
        q(
            "Value & Business",
            "Which statement is most consistent with modern PMP-style judgment and business environment thinking?",
            "Project success includes value worth the effort and expense, not just delivery against constraints.",
            "Project success is defined only by scope, schedule, and cost.",
            "Business context should be ignored to protect execution focus.",
            "Value should be considered only after final acceptance.",
        ),
        q(
            "Value & Business",
            "A project manager learns that a completed deliverable will soon be obsolete because the company changed strategy. What is the best next action?",
            "Surface the strategic misalignment and help leadership decide on course correction.",
            "Finish all remaining deliverables before mentioning the issue.",
            "Ask the team to work faster so the obsolete scope is completed sooner.",
            "Avoid discussing strategy because it is not a project concern.",
        ),
        q(
            "Value & Business",
            "A product team can either release a small but revenue-generating capability now or a larger feature bundle later. Which question matters most first?",
            "Which option better advances the intended benefits and strategic timing?",
            "Which option creates more internal documentation?",
            "Which option uses more of the remaining budget?",
            "Which option is preferred by the engineering manager personally?",
        ),
        q(
            "Value & Business",
            "A project manager is asked to continue a project whose main benefit metric has been flat for months. What should happen?",
            "Performance and expected value should be reevaluated before proceeding blindly.",
            "The metric should be removed because it is discouraging.",
            "The team should stop reporting benefit data to leadership.",
            "The project should expand scope so the metric eventually moves.",
        ),
        q(
            "Quality",
            "Which statement best reflects the PMBOK 7 quality principle?",
            "Quality means deliverables meet project objectives and stakeholder acceptance needs.",
            "Quality means producing the maximum possible feature count.",
            "Quality applies only to product testing, not project processes.",
            "Quality can be inspected in at the very end without earlier attention.",
        ),
        q(
            "Quality",
            "A team frequently passes internal tests but still disappoints users. What is most likely missing?",
            "Quality criteria are not fully aligned to stakeholder use and acceptance needs.",
            "The team is measuring too many user outcomes.",
            "The project uses too much tailoring.",
            "The sponsor attends too many reviews.",
        ),
        q(
            "Quality",
            "A project manager wants fewer escaped defects. What action is best first?",
            "Strengthen prevention and build quality into the way work is performed.",
            "Move all testing to the final week to improve focus.",
            "Hide low-severity defects to keep morale high.",
            "Reduce acceptance criteria so more work passes quickly.",
        ),
        q(
            "Quality",
            "A stakeholder says the team should skip documentation because only the final product matters. In a regulated environment, what is the best response?",
            "Required documentation can be part of quality because acceptance and compliance needs matter.",
            "Documentation never affects quality.",
            "Regulation should be ignored if the product works.",
            "Quality should be defined only by developer opinion.",
        ),
        q(
            "Quality",
            "Which action best supports both product and process quality?",
            "Ensuring deliverables meet acceptance criteria and the delivery process works effectively.",
            "Testing only after go-live.",
            "Ignoring process issues if the latest release shipped on time.",
            "Measuring only budget adherence.",
        ),
        q(
            "Quality",
            "A team is proud of fast delivery, but rework is increasing every month. What should the project manager do?",
            "Rebalance for sustainable quality rather than optimizing speed alone.",
            "Increase release frequency further and discuss rework later.",
            "Stop collecting defect data because it slows morale.",
            "Shift ownership of quality entirely to customers.",
        ),
        q(
            "Quality",
            "What is the strongest quality signal in a scenario-based PMP question?",
            "Deliverables align to defined acceptance needs and stakeholder use.",
            "The team says the solution is elegant.",
            "The sponsor likes the status deck design.",
            "The project manager avoided difficult conversations.",
        ),
        q(
            "Quality",
            "A release candidate meets technical specs but does not support accessibility requirements. What should the project manager do?",
            "Treat accessibility as part of quality and acceptance, not as an optional enhancement.",
            "Release anyway because accessibility can be addressed after launch.",
            "Ignore accessibility if most users are unaffected.",
            "Move the concern to procurement because it is not a project issue.",
        ),
        q(
            "Quality",
            "A project manager wants the team to improve quality without creating heavy bureaucracy. Which approach is best?",
            "Use fit-for-purpose quality practices that are effective in the project context.",
            "Add every possible checklist regardless of value.",
            "Eliminate quality reviews to preserve agility.",
            "Defer quality concerns to operations.",
        ),
        q(
            "Quality",
            "Which result best shows quality focus is working?",
            "Deliverables meet needs with less rework and more reliable acceptance.",
            "The issue log becomes longer every week.",
            "The team spends more time on status reports than on product work.",
            "No stakeholder ever asks a question at reviews.",
        ),
        q(
            "Complexity",
            "Which statement best reflects PMBOK 7 complexity guidance?",
            "Complexity can emerge from human behavior, uncertainty, ambiguity, and system interactions.",
            "Complexity exists only in large projects.",
            "Complexity is identical to budget variance.",
            "Complexity disappears once scope is approved.",
        ),
        q(
            "Complexity",
            "A project has stable scope but conflicting stakeholder agendas and many system dependencies. What should the project manager recognize?",
            "Complexity can be high even when scope is relatively stable.",
            "Complexity is low because scope is fixed.",
            "Only technical complexity matters here.",
            "Complexity belongs only to portfolio governance.",
        ),
        q(
            "Complexity",
            "A project manager notices small changes in one workstream are producing unpredictable effects elsewhere. Which principle is most relevant?",
            "Systems thinking.",
            "Procurement closeout.",
            "Resource smoothing only.",
            "Contract novation.",
        ),
        q(
            "Complexity",
            "What is a strong first response to rising project complexity?",
            "Increase awareness of interactions and adapt the approach deliberately.",
            "Assume the original plan will absorb all complexity.",
            "Stop engaging stakeholders so the system is simpler.",
            "Freeze all measurement activities.",
        ),
        q(
            "Complexity",
            "A project team treats every new ambiguity as a scheduling problem. What is the main risk?",
            "The team may miss the broader sources of complexity and choose weak responses.",
            "The team will automatically deliver faster.",
            "Ambiguity can always be solved by adding milestones.",
            "Stakeholder alignment improves when ambiguity is ignored.",
        ),
        q(
            "Adaptability & Change",
            "What best reflects the PMBOK 7 adaptability and resiliency principle?",
            "Build the capacity to respond to change and recover quickly from setbacks.",
            "Prevent all change through stricter baseline control.",
            "Accept setbacks as normal and avoid adjustment.",
            "Measure only output volume instead of outcomes.",
        ),
        q(
            "Adaptability & Change",
            "A critical supplier fails unexpectedly, but the team recovers quickly because backup options were prepared. Which capability is this?",
            "Resiliency.",
            "Procurement closure.",
            "Scope validation.",
            "Organizational decomposition.",
        ),
        q(
            "Adaptability & Change",
            "A team is resisting a necessary process change because the old process feels comfortable. What should the project manager do first?",
            "Explain the reason for the change and help the team adapt in a supported way.",
            "Impose the change without discussion because resistance is unprofessional.",
            "Delay the change indefinitely to avoid discomfort.",
            "Escalate all resistant team members to HR immediately.",
        ),
        q(
            "Adaptability & Change",
            "A product owner wants to preserve an outdated feature because it was important in the original vision. What should the project manager encourage?",
            "Focus on current outcomes and adapt priorities as context evolves.",
            "Preserve all original ideas to protect scope stability.",
            "Stop engaging users so priorities stop changing.",
            "Move the decision to procurement.",
        ),
        q(
            "Adaptability & Change",
            "A project team learns from each sprint and improves its working agreements. What principle is most visible?",
            "Adaptability and continuous improvement.",
            "Fixed-scope enforcement.",
            "Zero-based budgeting only.",
            "Formal contract administration.",
        ),
        q(
            "Ethics",
            "A vendor offers an expensive personal gift while contract negotiations are underway. What should the project manager do?",
            "Decline or handle it according to policy to avoid a conflict-of-interest situation.",
            "Accept it privately because it does not change the statement of work.",
            "Accept it if the vendor also lowers the price.",
            "Delay reporting it until the contract is signed.",
        ),
        q(
            "Ethics",
            "Which four values anchor PMI's Code of Ethics and Professional Conduct?",
            "Responsibility, respect, fairness, and honesty.",
            "Speed, loyalty, quality, and transparency.",
            "Authority, compliance, loyalty, and efficiency.",
            "Trust, cost control, hierarchy, and innovation.",
        ),
        q(
            "Ethics",
            "A sponsor pressures the project manager to omit a known risk from a steering report. What should the project manager do?",
            "Report honestly and professionally rather than hiding material information.",
            "Remove the risk because the sponsor owns the meeting.",
            "Mention the risk only verbally after the meeting ends.",
            "Wait until the risk occurs before disclosing it.",
        ),
        q(
            "Ethics",
            "Two suppliers submit equivalent bids, but one is owned by a close friend of the project manager. What is the best response?",
            "Disclose the conflict and follow a fair, documented selection process.",
            "Select the friend's company if its proposal looks slightly more polished.",
            "Keep the relationship private because the bids are similar.",
            "Let the team choose informally without records.",
        ),
        q(
            "Ethics",
            "A project manager discovers that actual progress has been overstated in a weekly report. What should happen first?",
            "Correct the information promptly and address the cause of the misreporting.",
            "Leave the report unchanged to protect team morale.",
            "Wait until month-end so the correction is less visible.",
            "Delete the report and avoid discussing it.",
        ),
        q(
            "AI & Sustainability",
            "A project team wants to use an AI tool to summarize stakeholder feedback. What is the best project manager response?",
            "Evaluate the tool's usefulness, risks, and governance implications before relying on it.",
            "Ban AI automatically because PMI exams treat it as unethical.",
            "Use the tool without review because it saves time.",
            "Delegate the decision entirely to the vendor.",
        ),
        q(
            "AI & Sustainability",
            "A sponsor asks whether AI should make backlog prioritization decisions automatically. What is the best answer?",
            "AI can inform decisions, but human judgment remains responsible for tradeoffs and accountability.",
            "Yes, AI should replace the product owner whenever enough data exists.",
            "No, AI should never appear in any project process.",
            "Only procurement can decide whether AI is allowed.",
        ),
        q(
            "AI & Sustainability",
            "A project manager is reviewing an AI-generated risk summary. What should happen next?",
            "Validate the output for context, bias, accuracy, and decision usefulness before acting on it.",
            "Adopt the summary immediately because AI outputs are objective.",
            "Ignore the summary entirely because AI has no place in projects.",
            "Replace the risk workshop with the AI summary permanently.",
        ),
        q(
            "AI & Sustainability",
            "A project adds a lower-energy hosting option that slightly increases setup effort but materially reduces operating impact. Which framing is best?",
            "Treat sustainability as a contextual planning and decision factor tied to value, quality, and risk.",
            "Ignore sustainability because it is unrelated to project delivery.",
            "Accept the greener option automatically without tradeoff analysis.",
            "Move the decision to closing because sustainability matters only after launch.",
        ),
        q(
            "AI & Sustainability",
            "A customer asks whether a new analytics solution uses personal data appropriately. What should the project manager do first?",
            "Review governance, compliance, and ethical implications before proceeding.",
            "Assure the customer everything is fine so the schedule is protected.",
            "Defer the concern until operations takes ownership.",
            "Remove the customer from technical discussions.",
        ),
    ]
)

QUESTION_BLUEPRINTS.extend(
    [
        q(
            "Project Work",
            "A project team can deliver the product, but operational readiness tasks are repeatedly neglected. What should the project manager do?",
            "Treat enabling work as part of the project work needed for successful outcomes.",
            "Assume operations will handle readiness after handoff.",
            "Drop readiness tasks because they are outside project scope by definition.",
            "Delay identifying readiness work until go-live week.",
        ),
        q(
            "Project Work",
            "A project manager inherits many open issues with no owners or due dates. What is the best next step?",
            "Establish disciplined issue ownership and follow-through as part of project operations.",
            "Close the issues so the list looks manageable.",
            "Move all issues into the risk register regardless of type.",
            "Ignore old issues and focus only on new work.",
        ),
        q(
            "Project Work",
            "A project team says every request becomes urgent. Which operational improvement would help most?",
            "Clarify intake, prioritization, and escalation paths for incoming work.",
            "Accept all work equally so no stakeholder feels ignored.",
            "Stop communicating with stakeholders about priority decisions.",
            "Measure only team utilization and ignore outcomes.",
        ),
        q(
            "Project Work",
            "A project manager wants the team to adapt faster when defects recur. What should the project manager strengthen?",
            "The learning environment and process discipline around analyzing recurring causes.",
            "The number of separate issue logs.",
            "The amount of manual rework accepted as normal.",
            "The distance between developers and testers.",
        ),
        q(
            "Project Work",
            "What is the best sign that project work processes are healthy?",
            "People know how work flows, issues are surfaced early, and operations support delivery effectively.",
            "No one ever asks questions about responsibility.",
            "Every request is approved instantly without review.",
            "The team uses more templates than last month.",
        ),
        q(
            "Project Work",
            "A project manager is deciding whether to add a lightweight kanban board for non-development activities. What is the best rationale?",
            "Visible workflow can improve coordination and smooth project operations.",
            "Boards are required only for software projects.",
            "Visualizing work removes the need for planning.",
            "Boards should replace all governance reporting automatically.",
        ),
        q(
            "Project Work",
            "A project involves regulated documents, training completion, and deployment logistics. Which statement is most accurate?",
            "These enabling activities are part of project work because they support successful outcomes.",
            "Only the technical product build counts as project work.",
            "Training and logistics belong only to operations and should not be tracked.",
            "Regulated documents should be created only after deployment.",
        ),
        q(
            "Project Work",
            "Team members are unclear whether an item is a risk, issue, or change request. What should the project manager do?",
            "Clarify working definitions and handling paths so operational flow improves.",
            "Treat everything as a change request to simplify administration.",
            "Tell the team to decide informally with no guidance.",
            "Stop categorizing items because labels do not matter.",
        ),
        q(
            "Project Work",
            "A project manager notices unnecessary approval loops between two internal teams. What should the project manager do first?",
            "Simplify the process where possible while preserving needed controls.",
            "Add more approvals to reduce error risk.",
            "Escalate every approval to the sponsor.",
            "Leave the process untouched because it is documented.",
        ),
        q(
            "Project Work",
            "Which artifact from PMI's models, methods, and artifacts set would commonly support project work?",
            "A risk register.",
            "A market share forecast for a competitor.",
            "An employee tax return.",
            "A board election roster.",
        ),
        q(
            "Project Work",
            "A team works hard but spends too much time searching for current versions of key files. What should the project manager address?",
            "The operational process for storing, versioning, and accessing project information.",
            "The sponsor's availability for steering meetings.",
            "The project's business case assumptions only.",
            "The decision to use hybrid delivery.",
        ),
        q(
            "Delivery",
            "A release is technically complete, but users say it does not solve the original business problem. What is the key lesson?",
            "Delivery must focus on outputs that drive intended outcomes and value.",
            "Technical completion is always sufficient for project success.",
            "Business outcomes belong only to portfolio management.",
            "User feedback should be collected only after project closeout.",
        ),
        q(
            "Delivery",
            "Which statement best describes the Delivery Performance Domain?",
            "It addresses delivering the scope and quality the project was undertaken to achieve.",
            "It is limited to handing off hardware at the final milestone.",
            "It applies only to agile teams releasing every sprint.",
            "It replaces measurement once deliverables are produced.",
        ),
        q(
            "Delivery",
            "A sponsor asks whether the team can skip acceptance testing to recover schedule. What should the project manager do?",
            "Protect the quality and acceptance expectations needed for the intended outcome.",
            "Skip testing because value delivery always means speed first.",
            "Defer all quality activities until after launch.",
            "Let the team decide privately without stakeholder input.",
        ),
        q(
            "Delivery",
            "A project is producing usable increments, but no one is confirming whether each increment meets stakeholder needs. What is missing?",
            "A deliberate connection between delivery and acceptance/value validation.",
            "A larger contingency budget only.",
            "More procurement documents.",
            "A stricter time-sheet policy.",
        ),
        q(
            "Delivery",
            "An internal platform team says its work is finished because the code was deployed, but support teams cannot operate it. What should the project manager conclude?",
            "Delivery is incomplete because the intended operational outcome has not been enabled.",
            "Deployment alone defines successful delivery.",
            "Operations readiness belongs outside project delivery.",
            "The sponsor should accept the gap because schedule was met.",
        ),
        q(
            "Delivery",
            "A project can either deliver all features late or deliver the highest-value subset on time. Which option is most aligned with PMBOK 7 value thinking?",
            "Deliver the option that best advances intended value, with transparent stakeholder agreement.",
            "Always deliver all features late because scope outranks value.",
            "Cut whichever features are cheapest without discussing benefits.",
            "Delay the decision until the last week of the project.",
        ),
        q(
            "Delivery",
            "A team wants to release a partially tested feature because leadership wants visible progress. What should the project manager do?",
            "Ensure the release meets agreed quality and acceptance expectations before delivery.",
            "Release it immediately because visible progress is the same as value.",
            "Hide the testing gap and fix it in operations later.",
            "Ask the team to redefine quality downward without stakeholder approval.",
        ),
        q(
            "Delivery",
            "A project aims to improve customer retention. The delivered system works, but customers still churn because onboarding is confusing. What should the project manager examine?",
            "Whether the delivered outputs are actually enabling the intended outcome.",
            "Only the internal team's utilization rate.",
            "Only the contract type.",
            "Only the project's original start date.",
        ),
        q(
            "Delivery",
            "What is the strongest reason to involve stakeholders in delivery reviews?",
            "To confirm that deliverables are meeting needs and moving toward intended outcomes.",
            "To transfer accountability away from the project team.",
            "To eliminate the need for acceptance criteria.",
            "To avoid measuring performance separately.",
        ),
        q(
            "Delivery",
            "A team is delivering exactly what was specified, but the market has changed and the product no longer differentiates the company. What should the project manager do first?",
            "Reassess delivery priorities against current business value and intended benefits.",
            "Continue unchanged because delivering specification is the only goal.",
            "Freeze stakeholder input until launch.",
            "Shift all decisions to the technical lead.",
        ),
        q(
            "Delivery",
            "A project supports strategy execution by solving a recurring operational problem. Which statement is most accurate?",
            "Projects create business value by delivering outputs that drive beneficial outcomes.",
            "Projects create value only when they produce revenue directly.",
            "Projects should avoid operational problem solving because that is not strategic.",
            "Business value is measured only at project closeout.",
        ),
        q(
            "Delivery",
            "A sponsor wants a final release with every possible feature, but data shows early partial releases would create benefits sooner. What should the project manager discuss?",
            "The tradeoff between delivery strategy and time-to-value.",
            "Only the team's preferred coding framework.",
            "Only the procurement closeout sequence.",
            "Only the team's vacation schedule.",
        ),
        q(
            "Delivery",
            "A product increment meets all acceptance criteria, but users say it is too difficult to use. What does this indicate?",
            "Acceptance criteria may have missed an important quality or usability need.",
            "Acceptance criteria are irrelevant to delivery.",
            "Usability concerns should never affect delivery decisions.",
            "The team should stop collecting user feedback.",
        ),
        q(
            "Delivery",
            "A project manager is prioritizing scope for an MVP release. What is the best criterion?",
            "The features most critical to achieving early stakeholder value and learning.",
            "The features that are easiest for the team to build regardless of value.",
            "The features requested most recently by the loudest stakeholder.",
            "The features that create the longest possible backlog.",
        ),
        q(
            "Delivery",
            "A project team produces deliverables at the planned cadence, but downstream teams cannot consume them. What should the project manager do first?",
            "Align delivery with the readiness and integration needs of the broader system.",
            "Speed up delivery even more so downstream teams adapt faster.",
            "Stop communicating with downstream teams to preserve focus.",
            "Treat the issue as outside project scope automatically.",
        ),
        q(
            "Delivery",
            "Which result best indicates successful delivery?",
            "The deliverables meet agreed quality expectations and support intended outcomes.",
            "The team worked long hours during the final month.",
            "No changes were ever requested.",
            "The project used the same method as the last project.",
        ),
        q(
            "Delivery",
            "A project manager discovers that a released feature created new manual work for customer support. What should the project manager do first?",
            "Evaluate the outcome impact and adjust delivery priorities or design accordingly.",
            "Ignore the support burden because the feature was delivered on time.",
            "Blame support for resisting change.",
            "Remove measurement reporting so the issue is less visible.",
        ),
        q(
            "Delivery",
            "Why can business value continue long after the project ends?",
            "Because deliverables can keep enabling benefits after handoff.",
            "Because project teams remain assigned permanently.",
            "Because every project converts automatically into operations.",
            "Because project governance continues indefinitely.",
        ),
        q(
            "Delivery",
            "A team is debating whether to delay release for one more quality fix or ship now. What should guide the decision?",
            "The impact on intended outcomes, stakeholder needs, and agreed quality expectations.",
            "The personal preference of the most senior developer.",
            "Whether the fix can be hidden from the sponsor.",
            "Whether the change log looks too long already.",
        ),
        q(
            "Delivery",
            "A customer asks for proof that each increment is moving the project toward benefits, not just output completion. What should the project manager emphasize?",
            "Outcome-oriented delivery measures and stakeholder validation.",
            "Only the number of tasks completed.",
            "Only the original budget baseline.",
            "Only the size of the defect log.",
        ),
        q(
            "Measurement",
            "Which statement best describes measurement in PMBOK 7?",
            "Measurement assesses performance and informs action to maintain acceptable outcomes.",
            "Measurement is a reporting formality used only at project closeout.",
            "Measurement is needed only for predictive projects.",
            "Measurement should focus only on schedule variance.",
        ),
        q(
            "Measurement",
            "A dashboard shows velocity increasing, but customer satisfaction is declining. What should the project manager conclude?",
            "One metric is insufficient; measurement should reflect outcomes and stakeholder value too.",
            "Velocity is the only valid performance measure in adaptive work.",
            "Customer satisfaction should not influence project decisions.",
            "The dashboard should be removed because it caused confusion.",
        ),
        q(
            "Measurement",
            "A project manager wants early warning of likely delivery problems. Which measurement approach helps most?",
            "Use timely indicators that reveal emerging variance before outcomes are missed.",
            "Wait for final milestone results because leading indicators are unreliable.",
            "Measure only team morale and ignore delivery performance.",
            "Measure cost only after all work is complete.",
        ),
        q(
            "Measurement",
            "The team reports many green indicators, yet stakeholders still say the project is off track. What should the project manager check first?",
            "Whether the measured indicators actually reflect the outcomes stakeholders care about.",
            "Whether more reports are needed with the same metrics.",
            "Whether the team should stop measuring altogether.",
            "Whether procurement should own performance reporting.",
        ),
        q(
            "Measurement",
            "A burnup chart shows scope growth faster than completion. What is the best first response?",
            "Review the trend with stakeholders and decide how to protect value, timing, or scope.",
            "Ignore the chart because burnup is informational only.",
            "Remove new scope items from the chart to improve optics.",
            "Cancel future measurement sessions.",
        ),
        q(
            "Measurement",
            "Which action best fits the Measurement Performance Domain?",
            "Using timely information to determine the right response to a variance.",
            "Avoiding performance data until final acceptance.",
            "Measuring only once because trends can distract the team.",
            "Treating every variance as a failure regardless of context.",
        ),
        q(
            "Measurement",
            "A project manager wants to measure whether a process change actually reduced cycle time. What is needed?",
            "A baseline, current performance data, and a way to compare results over time.",
            "Only a sponsor opinion after implementation.",
            "Only a retrospective with no data.",
            "Only the final project budget.",
        ),
        q(
            "Measurement",
            "A team delivers on time but quality complaints rise after each release. What should the project manager do first?",
            "Add or refine quality and outcome measures, not just schedule measures.",
            "Stop measuring complaints because releases remain on time.",
            "Reduce testing so the team can focus on delivery speed.",
            "Move all quality discussions to closing.",
        ),
        q(
            "Measurement",
            "Which measure is most useful when the project goal is customer adoption?",
            "A measure tied to actual usage or customer uptake.",
            "The number of meeting minutes produced.",
            "The total count of project emails sent.",
            "The number of folders created in the repository.",
        ),
        q(
            "Measurement",
            "A team says measurement feels punitive, so people hide bad news. What should the project manager do?",
            "Use measurement as a learning and decision tool rather than as a blame mechanism.",
            "Stop measuring so trust can improve naturally.",
            "Publicly compare individual metrics every week.",
            "Report only positive indicators to leadership.",
        ),
        q(
            "Measurement",
            "A project manager is evaluating a dashboard with twenty metrics. Most are rarely used for decisions. What should the project manager do?",
            "Reduce the set to metrics that meaningfully support decisions and outcomes.",
            "Add more metrics so nothing is missed.",
            "Keep all metrics because more data is always better.",
            "Replace the dashboard with narrative status only.",
        ),
        q(
            "Measurement",
            "A predictive project has EV lower than PV and AC higher than EV. What is the main interpretation?",
            "The project is behind schedule and over budget.",
            "The project is ahead of schedule and under budget.",
            "The project is on schedule but over quality targets.",
            "No interpretation is possible without stakeholder mapping.",
        ),
        q(
            "Measurement",
            "A team wants to know whether a newly introduced WIP limit is helping. Which measure is most relevant?",
            "Flow-related measures such as cycle time and throughput trends.",
            "The original business case only.",
            "The number of sponsors on the steering committee.",
            "The count of signed purchase orders.",
        ),
        q(
            "Measurement",
            "A project manager sees improving metrics, but the underlying data is delayed by three weeks. What is the risk?",
            "Decisions may be made too late because the information is not timely enough.",
            "The metrics are automatically more accurate because they are delayed.",
            "Timeliness does not matter if the trend looks positive.",
            "Delayed data eliminates the need for forecasts.",
        ),
        q(
            "Measurement",
            "What is the strongest reason to define measurement early?",
            "It clarifies what success looks like and enables course correction while there is still time to act.",
            "It prevents any future tailoring of the project.",
            "It guarantees there will be no change requests.",
            "It makes stakeholder engagement unnecessary.",
        ),
    ]
)

QUESTION_BLUEPRINTS.extend(
    [
        q(
            "Approach & Life Cycle",
            "A project includes an exploratory proof of concept before a regulated rollout. What is the most appropriate high-level life cycle choice?",
            "Use an adaptive or exploratory phase early and a more predictive rollout later.",
            "Use one fixed predictive life cycle for all work regardless of uncertainty.",
            "Use only adaptive delivery because regulation can be handled after deployment.",
            "Delay deciding on the life cycle until all work is complete.",
        ),
        q(
            "Approach & Life Cycle",
            "A team is delivering every two weeks, but dependent teams release quarterly. What should the project manager do first?",
            "Coordinate delivery cadence and integration points across the broader system.",
            "Force every team to move to the same tool immediately.",
            "Ignore the difference because local optimization is enough.",
            "Reduce the team's cadence to annual releases.",
        ),
        q(
            "Approach & Life Cycle",
            "Which statement best describes the relationship among deliverables, approach, cadence, and life cycle?",
            "Deliverables influence approach; approach influences cadence; cadence influences life cycle structure.",
            "Cadence determines deliverables, and deliverables should never affect approach.",
            "Life cycle phases should be set before understanding the deliverables.",
            "These elements are independent and should be managed separately.",
        ),
        q(
            "Approach & Life Cycle",
            "A project manager wants to adopt agile because it is popular, but customer approvals require signed design packages before build. What should happen first?",
            "Evaluate the real constraints and tailor an approach that fits them.",
            "Adopt agile anyway and handle approvals informally.",
            "Convince the customer to drop all approvals before planning starts.",
            "Use predictive only because approvals automatically prohibit iteration.",
        ),
        q(
            "Approach & Life Cycle",
            "Which approach best fits work with low uncertainty and a single integrated final handoff?",
            "Predictive.",
            "Adaptive.",
            "Continuous experimentation.",
            "No life cycle definition.",
        ),
        q(
            "Approach & Life Cycle",
            "A project manager is told to use a standard organizational methodology even though the project is unusually small and low risk. What should the project manager do?",
            "Tailor the organizational approach appropriately while honoring required governance constraints.",
            "Use the full methodology unchanged because all projects must be identical.",
            "Ignore the organization and invent a totally new framework.",
            "Avoid documenting any tailoring decisions.",
        ),
        q(
            "Approach & Life Cycle",
            "Which action best supports ongoing improvement in a chosen development approach?",
            "Inspecting outcomes and adjusting the way of working through retrospectives and lessons learned.",
            "Preventing any process changes after the first baseline approval.",
            "Measuring only schedule variance and ignoring team feedback.",
            "Keeping practices unchanged so results remain comparable.",
        ),
        q(
            "Approach & Life Cycle",
            "A company wants every project to use adaptive delivery, but a vendor contract fixes scope, sequence, and milestone approvals. What should the project manager do first?",
            "Recognize the constraint and propose a context-appropriate approach rather than forcing a single method.",
            "Pretend the contract is flexible and operate adaptively anyway.",
            "Convert all milestones into optional checkpoints.",
            "Ask the team to ignore the contract and focus on faster delivery.",
        ),
        q(
            "Approach & Life Cycle",
            "A project has uncertain requirements but a hard compliance deadline. Which rationale best supports a hybrid approach?",
            "Hybrid can accommodate uncertainty in some work while preserving deadline-driven control where needed.",
            "Hybrid guarantees the deadline without any tradeoffs.",
            "Hybrid removes the need for stakeholder engagement.",
            "Hybrid should be used whenever the budget is small.",
        ),
        q(
            "Approach & Life Cycle",
            "What is the best sign that the current approach should be revisited?",
            "The context changed enough that the approach no longer supports effective value delivery.",
            "A team member prefers a different tool.",
            "One status meeting ran long.",
            "The sponsor has not asked for a change explicitly.",
        ),
        q(
            "Planning",
            "In PMBOK 7, which statement best reflects planning?",
            "Planning is ongoing and evolves as the project learns and changes.",
            "Planning is completed once at the start and then archived.",
            "Planning is needed only for predictive projects.",
            "Planning should be minimized to reduce stakeholder involvement.",
        ),
        q(
            "Planning",
            "A team starts execution quickly but later discovers major dependency conflicts. What planning weakness is most likely?",
            "Insufficient coordination of evolving work and dependencies.",
            "Too much stakeholder engagement.",
            "Excessive team empowerment.",
            "Overuse of lessons learned.",
        ),
        q(
            "Planning",
            "A project manager is preparing for a large cross-functional rollout. Which activity is most important first?",
            "Clarify outcomes, constraints, dependencies, and how work will be coordinated.",
            "Finalize every low-level task estimate before discussing objectives.",
            "Delay planning until procurement is complete.",
            "Set the baseline before talking with stakeholders.",
        ),
        q(
            "Planning",
            "A sponsor says planning is taking too long. What is the best response?",
            "Explain that planning should be fit for purpose and sufficient to coordinate successful delivery.",
            "Agree and stop planning altogether so execution can begin immediately.",
            "Insist on detailed planning for all work regardless of uncertainty.",
            "Move all planning responsibility to the team and disengage.",
        ),
        q(
            "Planning",
            "A project in an uncertain environment needs to begin quickly. Which planning approach is best?",
            "Plan enough to start intelligently, then elaborate as learning occurs.",
            "Wait until every detail is known before beginning any work.",
            "Skip planning because uncertainty makes planning pointless.",
            "Lock all scope, schedule, and cost assumptions permanently on day one.",
        ),
        q(
            "Planning",
            "A hybrid team has a roadmap but no clear integration points between predictive and adaptive workstreams. What should the project manager do?",
            "Plan the coordination points explicitly so the workstreams support one another.",
            "Allow each workstream to operate independently with no shared milestones.",
            "Convert all adaptive work to predictive immediately.",
            "Delay planning until both workstreams are finished.",
        ),
        q(
            "Planning",
            "Which statement best reflects the Planning Performance Domain?",
            "It addresses the initial, ongoing, and evolving organization and coordination needed for outcomes.",
            "It applies only to creating the initial project charter.",
            "It focuses only on cost estimating.",
            "It replaces stakeholder engagement once planning is complete.",
        ),
        q(
            "Planning",
            "A team keeps replanning because the objective itself is vague. What should the project manager address first?",
            "The clarity of intended outcomes and success criteria.",
            "The team's velocity target.",
            "The procurement closeout checklist.",
            "The frequency of retrospectives.",
        ),
        q(
            "Planning",
            "A project manager wants to improve planning quality in a new domain where the team lacks experience. Which method is most helpful?",
            "Use expert input and collaborative estimation to improve assumptions.",
            "Reduce planning activities because the team is uncertain.",
            "Commit to fixed dates first and estimate later.",
            "Avoid documenting assumptions so they cannot be challenged.",
        ),
        q(
            "Planning",
            "What should happen to assumptions identified during planning?",
            "They should be made visible and revisited as the project progresses.",
            "They should be hidden to avoid stakeholder concern.",
            "They should be removed from documentation once approved.",
            "They are relevant only in predictive environments.",
        ),
        q(
            "Planning",
            "A project manager notices the team plans features but not the transition into operations. What is missing?",
            "Planning for the broader outcomes and enabling work around delivery.",
            "A stronger conflict resolution policy only.",
            "More detailed task naming conventions.",
            "A lower-level coding standard.",
        ),
        q(
            "Planning",
            "A team frequently starts work before clarifying dependencies, acceptance criteria, or decision owners. What is the most likely result?",
            "Rework and coordination failures that reduce value delivery.",
            "Faster execution with no tradeoff.",
            "Automatic stakeholder alignment.",
            "Lower uncertainty because action replaces planning.",
        ),
        q(
            "Planning",
            "A project manager in an adaptive environment asks whether a detailed milestone plan is still useful. What is the best answer?",
            "It can be useful if it supports decision making and coordination without becoming overly rigid.",
            "No milestone thinking is ever useful in adaptive work.",
            "Detailed milestones should replace all backlog planning.",
            "Milestones are only valid for procurement teams.",
        ),
        q(
            "Planning",
            "Which planning action best supports better decision making later?",
            "Defining how progress, value, quality, and risks will be assessed.",
            "Avoiding measurement because it can constrain innovation.",
            "Keeping benefits unspoken until closing.",
            "Planning only for best-case scenarios.",
        ),
        q(
            "Planning",
            "A sponsor wants a final date now, but multiple external dependencies are still unresolved. What should the project manager do first?",
            "Communicate the uncertainty and plan with transparent assumptions and dependency tracking.",
            "Provide a date with no explanation because leadership needs confidence.",
            "Refuse to give any information until all dependencies are resolved.",
            "Choose the most optimistic date to secure support.",
        ),
        q(
            "Planning",
            "A project starts with a solid plan, but the business environment changes after a competitor launches a similar product. What should happen next?",
            "Revisit plans to ensure continued alignment to value and objectives.",
            "Keep the plan unchanged to preserve control.",
            "Restart the project from initiation regardless of impact.",
            "Transfer ownership of planning to marketing.",
        ),
        q(
            "Planning",
            "What is the most useful planning mindset in PMBOK 7?",
            "Coordinate work intentionally while remaining ready to adapt.",
            "Plan once, then protect the plan from change.",
            "Avoid planning details and rely only on intuition.",
            "Maximize documentation even if it slows delivery with no decision benefit.",
        ),
        q(
            "Planning",
            "A team is asked to commit to more work than its capacity supports. What should the project manager do?",
            "Use transparent planning data to negotiate a feasible commitment.",
            "Accept the extra work and trust the team to work harder.",
            "Hide the capacity issue until after the deadline passes.",
            "Add all requested work and drop quality controls later if needed.",
        ),
        q(
            "Planning",
            "Planning varies by product, development approach, environment, and stakeholders. What does this imply?",
            "The amount, timing, and frequency of planning should be tailored.",
            "Planning standards should be identical for every project.",
            "Stakeholders should not influence planning frequency.",
            "Environment matters only during execution.",
        ),
        q(
            "Planning",
            "A project manager is leading work with recurring small changes from users. Which planning pattern is most appropriate?",
            "Use rolling-wave or iterative planning with regular reprioritization.",
            "Freeze all planning outputs for the life of the project.",
            "Plan only the final acceptance event.",
            "Avoid updating plans to preserve baseline stability.",
        ),
        q(
            "Project Work",
            "A project has clear plans but poor day-to-day execution discipline. Documents are current, yet blockers remain unresolved for weeks. What should the project manager improve first?",
            "The operating system of project work, including communication, escalation, and issue handling.",
            "The number of planning workshops.",
            "The business case approval cycle.",
            "The sponsor's attendance at kickoffs only.",
        ),
        q(
            "Project Work",
            "Which activity belongs most directly to the Project Work Performance Domain?",
            "Managing the processes and resources that keep project operations running smoothly.",
            "Selecting the corporate strategy portfolio.",
            "Defining the organization's compensation system.",
            "Approving mergers and acquisitions.",
        ),
        q(
            "Project Work",
            "Procurement lead times are disrupting delivery because the team learned too late that equipment had a 14-week wait. What should the project manager do first?",
            "Integrate procurement visibility into project work and coordination earlier.",
            "Reduce quality checks to recover schedule immediately.",
            "Ask the team to work around the missing equipment permanently.",
            "Move all procurement decisions to project closing.",
        ),
        q(
            "Project Work",
            "A project manager notices that physical resources are available, but no one knows who is using what and when. What is the main risk?",
            "Operational inefficiency and avoidable delays in project work.",
            "Too much stakeholder engagement.",
            "Excessive value delivery.",
            "Overplanning of benefits realization.",
        ),
        q(
            "Project Work",
            "A learning culture on a project most directly supports which outcome?",
            "Improved performance through adaptation, transparency, and continuous improvement.",
            "Elimination of all risk.",
            "No need for governance reviews.",
            "Stable requirements in every environment.",
        ),
        q(
            "Project Work",
            "Team members keep solving the same problem repeatedly because no one captures or shares what was learned. What should the project manager do?",
            "Create lightweight learning loops so insights are applied during ongoing work.",
            "Wait for final lessons learned at project closeout.",
            "Avoid documenting learning because it adds overhead.",
            "Escalate each repeated problem separately to the sponsor.",
        ),
        q(
            "Project Work",
            "Project communications are frequent, but people still say they do not know who is doing what. What should the project manager improve?",
            "The usefulness and clarity of operational communication, not just its volume.",
            "The number of reports only.",
            "The project charter version number.",
            "The stakeholder register format only.",
        ),
        q(
            "Project Work",
            "A team is executing well, but handoffs between design and testing repeatedly fail. Which action is best?",
            "Improve the process and interfaces that govern the handoff work.",
            "Replace the entire testing team immediately.",
            "Stop measuring handoff quality to reduce pressure.",
            "Add more approval signatures without changing the process.",
        ),
        q(
            "Project Work",
            "A vendor's work is technically sound, but invoice timing and contract reporting are causing project friction. Which domain concern is this closest to?",
            "Managing project work and procurements so operations run smoothly.",
            "Selecting a development approach.",
            "Building team motivation through rewards.",
            "Choosing portfolio investments.",
        ),
        q(
            "Project Work",
            "Which action most directly supports smoother project work in a distributed team?",
            "Making workflows, ownership, and current status visible across the team.",
            "Reducing all written communication to one monthly email.",
            "Requiring every issue to wait for the next steering committee.",
            "Avoiding cross-functional discussions to save time.",
        ),
    ]
)


def build_bank() -> dict:
    assert len(QUESTION_BLUEPRINTS) == 200, f"Expected 200 questions, found {len(QUESTION_BLUEPRINTS)}"

    questions = []
    for prompt_number, item in enumerate(QUESTION_BLUEPRINTS, start=1):
        topic, stem, correct, distractors = item
        questions.append(build_question(prompt_number, topic, stem, correct, distractors))

    return {
        "id": BANK_ID,
        "title": BANK_TITLE,
        "source": BANK_SOURCE,
        "totalQuestions": len(questions),
        "questions": questions,
    }


def update_questions_json() -> None:
    payload = json.loads(QUESTIONS_PATH.read_text(encoding="utf-8"))
    banks = payload.get("banks", [])

    new_bank = build_bank()
    replaced = False
    for index, bank in enumerate(banks):
        if bank.get("id") == BANK_ID:
            banks[index] = new_bank
            replaced = True
            break

    if not replaced:
        banks.append(new_bank)

    payload["banks"] = banks
    payload["totalQuestions"] = sum(len(bank.get("questions", [])) for bank in banks)

    QUESTIONS_PATH.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"Updated {QUESTIONS_PATH} with bank '{BANK_TITLE}' ({new_bank['totalQuestions']} questions).")
    print(f"Total questions across all banks: {payload['totalQuestions']}")


if __name__ == "__main__":
    update_questions_json()
